- alias: CCTV Loop
  id: cctv_video_loop_continuous
  description: Cycles randomly through local CCTV videos every 8 seconds.
  trigger:
    - platform: time_pattern
      seconds: "/6"
  condition: []
  action:
    - service: input_text.set_value
      target:
        entity_id: input_text.random_video_filename
      data:
        value: >
          {% set max_val = 3 %}
          a{{ range(1, max_val + 1) | random }}.mp4
  mode: single